name: Deployment

on: 
    push:
        branches: [master]
    
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Build and publish Apache2 PHP image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nemjit001/default-website
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "Apache-PHP"
      - name: Build and publish NGINX image
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: nemjit001/default-website
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: "nginx"
